name: Ubuntu ton_crypto_lib build (portable, x86-64)

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - run: |
        sudo apt update
        sudo apt install -y apt-utils 

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Build TON
      run: |
        cp assembly/nix/build-toncryptolib-linux-x86-64-nix.sh .
        chmod +x build-toncryptolib-linux-x86-64-nix.sh
        ./build-toncryptolib-linux-x86-64-nix.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton_crypto_lib-x86_64-linux
        path: artifacts
