name: MacOS ton_crypto_lib build (portable, x86-64)

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build TON
        run: |
          cp assembly/nix/build-toncryptolib-macos-nix.sh .
          chmod +x build-toncryptolib-macos-nix.sh
          ./build-toncryptolib-macos-nix.sh -t

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ton_crypto_lib-x86_64-macos
          path: artifacts
