name: Windows ton_crypto_lib build (portable, x86-64)

on: [push,workflow_dispatch,workflow_call]

defaults:
  run:
    shell: cmd

jobs:
  build:

    runs-on: windows-2022

    steps:
      - name: Get Current OS version
        run: |
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Check out current repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build TON
        run: |
          copy assembly\native\build-toncryptolib-windows-github.bat .
          copy assembly\native\build-toncryptolib-windows.bat .
          build-toncryptolib-windows-github.bat Enterprise

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: toncryptolib-win
          path: artifacts